In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv(r"D:\Downloads From Browser\netflix_users.csv")
df.head()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User_ID            25000 non-null  int64
 1   Name               25000 non-null  object
 2   Age                25000 non-null  int64
 3   Country            25000 non-null  object
 4   Subscription_Type  25000 non-null  object
 5   Watch_Time_Hours   25000 non-null  float64
 6   Favorite_Genre     25000 non-null  object
 7   Last_Login         25000 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.5+ MB

In [10]:
df.isnull().sum() #no null values found

User_ID              0
Name                 0
Age                  0
Country              0
Subscription_Type    0
Watch_Time_Hours     0
Favorite_Genre       0
Last_Login           0
dtype: int64

In [8]:
df.describe()

            User_ID           Age  Watch_Time_Hours
count  25000.000000  25000.000000      25000.000000
mean   12500.500000     46.482880        500.468858
std     7217.022701     19.594861        286.381815
min        1.000000     13.000000          0.120000
25%     6250.750000     29.000000        256.567500
50%    12500.500000     46.000000        501.505000
75%    18750.250000     63.000000        745.732500
max    25000.000000     80.000000        999.990000

In [13]:
df.duplicated() # no duplicate value found

0        False
1        False
2        False
3        False
4        False
         ...
24995    False
24996    False
24997    False
24998    False
24999    False
Length: 25000, dtype: bool

In [14]:
df.dtypes

User_ID                int64
Name                  object
Age                    int64
Country               object
Subscription_Type     object
Watch_Time_Hours     float64
Favorite_Genre        object
Last_Login            object
dtype: object